#' Infections on one day in the network model
#'
#' @author Lewis Spurgin
#' @author Joel Hellewell
#'
#' @param day number of days from start of the inection - must be > 0
#' @param case_data data.frame of cases in outbreak so far; initially generated by outbreak_setup
#' @param net network from which to sample cases, in pairwise list format.
#' @param prop.asym proportion of asymptomtaic cases (must be 0<=x<=1)
#' @param incfn function samples from incubation period; generated by dist_setup
#' @param delayfn function samples from the onset-to-hospitalisation delay; generated by dist_setup
#' @param prop.ascertain numeric proportion of infectious contacts ascertained by contact tracing (must be 0<=x<=1)
#' @param presymrate the proportion of cases with pre-onset transmission (must be 0<=x<=1)
#' @param R scaling factor for infection probability
#' @param quarantine logical whether quarantine is in effect, if TRUE then traced contacts are isolated before symptom onset
#' @param tracing logical whether tracing is in effect
#' @param isolation logical whether isolation is in effect
#' @param secondary logical whether secondary contact tracing is in effect
#' @param outside daily probability of infection from outside the network
#' @param testing logical whether testing is in effect
#' @param cap_max_tests integer - maximum number of tests
#' @rawNamespace import(dplyr, except = c(union,as_data_frame,groups))
#' @importFrom tibble tibble
#' @importFrom purrr map2 map2_dbl map_lgl rbernoulli
#' @importFrom magrittr %>% %<>%
#'
#' @return
#' @export
#'
#' @examples
#'
#' \dontrun{
#' load("data-raw/am_list.RData")
#' haslemere <- format_network(am_list[[1]])
#' # incubation period sampling function
#' incfn <- dist_setup(dist_shape = 2.322737,dist_scale = 6.492272)
#' # delay distribution sampling function
#' delayfn <- dist_setup(1, 1.4)
#' # generate initial cases
#' case_data <- outbreak_setup(net = haslemere, num.initial.cases = 1,incfn,delayfn,prop.asym=0.4, isolation = TRUE)
#' # generate next generation of cases
#' outbreak_step(day = 1, case_data = case_data,net = haslemere, prop.asym = 0.4, incfn = incfn, delayfn = delayfn, prop.ascertain = 1,
#' presymrate = 0.2, R = 0.8, quarantine = TRUE, isolation = TRUE, tracing = TRUE, secondary = TRUE, outside = 0.001, testing = FALSE,test_neg = 0.1)
#' }

outbreak_step <- function(day, case_data, net = haslemere,
                          prop.asym, incfn, delayfn,
                          prop.ascertain, presymrate, R, quarantine,
                          isolation, tracing,
                          secondary, outside,
                          testing = FALSE,
                          cap_max_tests = NULL,
                          test_neg) {


  # Rename some variables ---------------------------------------------------

  newnet <- net
  colnames(newnet) <- c("caseid","contact","rate")



  # Update isolation, quarantine and infection status -----------------------------------
  if(isolation) {

    new_isolations <- which(day > case_data$isolated_time)
    if(quarantine){
      new_quarantines <- which(day > case_data$quarantine_time)
    }
    new_releases <- which(day > case_data$release_time)


    case_data$isolated[new_isolations] <- TRUE
    if(quarantine){case_data$quarantined[new_quarantines] <- TRUE}
    case_data$isolated[new_releases] <- FALSE
    case_data$quarantined[new_releases] <- FALSE



    #Reset isolation, release and test time for individuals who didn't undergo full isolation or quarantine
    early_releases <- c(new_releases[case_data$release_time[new_releases] <
                                       (case_data$isolated_time[new_releases] + 14)],
                        new_releases[case_data$release_time[new_releases] <
                                       (case_data$quarantine_time[new_releases] + 14)])
    case_data$isolated_time[early_releases] <- Inf
    case_data$test_time[early_releases] <- Inf
    case_data$release_time[early_releases] <- Inf
    case_data$quarantine_time[early_releases] <- Inf
  }

  #Assign recovered status to recovered individuals
  recovered <- which(day > case_data$recovery_time)
  case_data$status[recovered] <- "R"






  # Add infections from outside ---------------------------------------------

  if(outside > 0) {
    potential_new_inf<- which(case_data$status == "S" & !case_data$isolated & !case_data$quarantined)
    new_infections <- potential_new_inf[rbernoulli(length(potential_new_inf),
                                                   p = outside)]

    case_data$exposure[new_infections] <- day
    case_data$onset[new_infections] <- day + incfn(length(new_infections))
    case_data$recovery_time[new_infections] <- case_data$onset[new_infections] + 7
    case_data$status[new_infections] <- "I"

    #Isolation times for symtpomatic new infections
    if(isolation)
    {
      sym_cases <- new_infections[!case_data$asym[new_infections]]
      case_data$isolated_time[sym_cases] <- case_data$onset[sym_cases] +
        delayfn(length(sym_cases))
      case_data$release_time[sym_cases] <- case_data$isolated_time[sym_cases] + 14
    }
  }


  # Pull out infectious inds who are not isolated
  infectors <- dplyr::filter(case_data, status == "I", !isolated)






  # New cases  ----------------------------

  #Get contacts of infectious inds from network
  new_cases <- dplyr::filter(newnet,
                             caseid %in% infectors$caseid,
                             rate > 0)

  new_inf_rows <- match(new_cases$contact,
                        case_data$caseid)

  #Only keep susceptible contacts who are not isolated
  new_cases <- new_cases[case_data$status[new_inf_rows] == "S" &
                           !case_data$isolated[new_inf_rows] &
                           !case_data$quarantined[new_inf_rows],]






  # Generate new infections -------------------------------------------------

  if(nrow(new_cases) > 0) {

    #Filter based on probability that each contact is infected
    infector_rows <- match(new_cases$caseid,
                           case_data$caseid)

    asymrate <- ifelse(case_data$asym[infector_rows],0.5,1)

    infected <- rbernoulli(nrow(new_cases),
                           p = inf_prob(day = rep(day,length(infector_rows)),
                                        inc_samp = case_data$onset[infector_rows],
                                        contactrate = new_cases$rate,
                                        theta = presymrate,
                                        infasym = asymrate,
                                        R = R))

    #Each contact can only be infected once
    new_cases <- new_cases[infected,] %>%
      group_by(contact) %>%
      slice_sample(1)

  }






  # Compile data for all new infections -------------------------------------


  # Compile a data frame for all new cases, new_cases is the amount of people that each infector has infected

  if(nrow(new_cases) > 0){

    prob_samples <- match(new_cases$contact,case_data$caseid)
    case_data$infector[prob_samples] <- case_data$caseid[match(new_cases$caseid,
                                                               case_data$caseid)]
    case_data$exposure[prob_samples] <- day
    case_data$status[prob_samples] <- "I"
    case_data$onset[prob_samples] <- day + incfn(length(prob_samples))
    case_data$recovery_time[prob_samples] <- case_data$onset[prob_samples] + 7

    #Isolation times for symtpomatic cases
    if(isolation) {
      sym_cases <- prob_samples[!case_data$asym[prob_samples]]
      case_data$isolated_time[sym_cases] <- case_data$onset[sym_cases] +
        delayfn(length(sym_cases))
      case_data$release_time[sym_cases] <- case_data$isolated_time[sym_cases] + 14

    }

  }






  # Contact tracing ---------------------------------------------------------

  #Empty vector of contacts
  traced_contacts <- c()


  if(tracing) {
    #get contacts of symptomatic infectors who onset yesterday
    new_ill <- filter(case_data,
                      status == "I",
                      !asym,
                      onset < day,
                      onset > (day - 1))

    if(nrow(new_ill) > 0){

      #Get contacts of infectious inds from network
      case_contacts <- filter(newnet,
                              caseid %in% new_ill$caseid,
                              rate > 0)

      new_contact_rows <- match(case_contacts$contact,
                                case_data$caseid)

      #Only keep contacts who are not isolated and not recovered
      traced_contacts <- case_contacts[case_data$status[new_contact_rows] != "R" &
                                         !case_data$isolated[new_contact_rows] &
                                         !case_data$quarantined[new_contact_rows],]
      traced_contacts <- traced_contacts$contact[rbernoulli(length(traced_contacts$contact),
                                                            p = prop.ascertain)]
    }

  }


  # Secondary contact tracing ----------------



  #Estimate whether secondary contacts are traced
  if(secondary) {
    if(nrow(new_ill) > 0) {
      if(nrow(case_contacts) > 0) {

        sec_contacts <- filter(newnet,
                               caseid %in% case_contacts$contact,
                               rate > 0)

        new_contact_rows <- match(sec_contacts$contact,
                                  case_data$caseid)


        #Only keep secondary contacts who are not isolated and not recovered
        traced_sec_contacts <- sec_contacts[case_data$status[new_contact_rows] != "R" &
                                              !case_data$isolated[new_contact_rows] &
                                              !case_data$quarantined[new_contact_rows],]

        #Filter based on ascertainment rate
        traced_sec_contacts <- traced_sec_contacts$contact[rbernoulli(length(traced_sec_contacts$contact),
                                                                      p = prop.ascertain)]


        #Add to list of traced contacts
        traced_contacts <- unique(c(traced_contacts,
                                    traced_sec_contacts))
      }
    }
  }







# Set quarantine times based on tracing -----------------------------------

  if(isolation & tracing & length(traced_contacts) > 0) {

    if(quarantine) {
      #If you are recovered and asymptomatic and traced, you isolate
      recovered_traced <- which(case_data$caseid %in% traced_contacts &
                                  case_data$status == "R" &
                                  case_data$asym)
      case_data$quarantine_time[recovered_traced] <- day+delayfn(length(recovered_traced))

      #If you are susceptible you quarantine on being traced
      susceptible_traced <- which(case_data$caseid %in% traced_contacts &
                                    case_data$status == "S")

      case_data$quarantine_time[susceptible_traced] <- day+delayfn(length(susceptible_traced))

      #If you are infectious you isolate if the delay is shorter than your current iso time
      infectious_traced <- which(case_data$caseid %in% traced_contacts &
                                   case_data$status == "I")
      new_iso_time <- day + delayfn(length(infectious_traced))
      case_data$quarantine_time[infectious_traced] <-  day + delayfn(length(infectious_traced))
    } else {

      #If you're susceptible and there's no quarantine and you're traced
      #You isolate immediately at symptom onset
      susceptible_traced <- which(case_data$caseid %in% traced_contacts &
                                    case_data$status == "S" &
                                    !case_data$asym)

      case_data$isolated_time[susceptible_traced] <- case_data$onset[susceptible_traced]

      #If you're infectious and traced and no quarantine, you also isolate at onset
      infectious_traced <- which(case_data$caseid %in% traced_contacts &
                                   case_data$status == "I" &
                                   !case_data$asym)

      case_data$isolated_time[infectious_traced] <- case_data$onset[infectious_traced]

    }

    case_data$release_time <- ifelse(case_data$isolated_time < case_data$quarantine_time,
                                     case_data$isolated_time + 14,
                                     case_data$quarantine_time + 14)

  }



  # Test and release quarantined and isolated cases ------------------------------------

  if(testing)
  {
    #Identify untested inds and assign a test time based on their isolation and quarantine time
    untested <- which(case_data$test_time == Inf)
    case_data$test_time[untested] <- ifelse(case_data$isolated_time[untested] < case_data$quarantine_time[untested],
                                            case_data$isolated_time[untested],
                                            case_data$quarantine_time[untested]) +
      delayfn(length(untested))

    #Today's tests
    new_tests <- which(day < case_data$test_time &
                         (day+1) > case_data$test_time)

    #If there's a test cap randomly sample tests to be excluded and reset their test time
    if(length(new_tests) > cap_max_tests) {
      not_tested <- new_tests[sample(1:length(new_tests),length(new_tests)-cap_max_tests)]
      case_data$test_time[not_tested] <- Inf
      new_tests <- new_tests[!(new_tests %in% not_tested)]
    }


    #Run tests
    #90% chance of testing positive
    #2% false positive rate

    test_results <- (case_data$status[new_tests] == "I" &
                       rbernoulli(length(new_tests),
                                  1-test_neg)) |
      rbernoulli(length(new_tests), 0.02)


    negative_tests <- new_tests[!test_results]

    case_data$release_time[negative_tests] <- case_data$test_time[negative_tests]

  }




  return(case_data)
}



